import { describe, expect, it } from 'vitest';
import type { Direction } from './floorGenerator';
import type { Door, EnemySpawn, PickupSpawn, Tile } from './roomGenerator';
import { validateRoom, type Symmetry } from './roomValidator';
import type { Crusher } from './crusher';

const DOOR_CELLS: Record<Direction, { x: number; y: number }> = {
  up: { x: 6, y: 0 },
  down: { x: 6, y: 6 },
  left: { x: 0, y: 3 },
  right: { x: 12, y: 3 },
};

/**
 * Builds a 13x7 room from a picture: `.` floor, `#` stone, `o` hole, `x` thorn, `Z` zombie,
 * `T` turret and `$` a heart, the last three standing on floor.
 */
function room(picture: string, doors: Direction[] = ['up', 'down', 'left', 'right']) {
  const rows = picture.trim().split('\n').map((r) => r.trim());
  const enemies: EnemySpawn[] = [];
  const pickups: PickupSpawn[] = [];
  const tiles: Tile[][] = rows.map((row, y) =>
    [...row].map((ch, x): Tile => {
      if (ch === 'Z') enemies.push({ type: 'zombie', cell: { x, y } });
      if (ch === 'T') enemies.push({ type: 'turret', cell: { x, y } });
      if (ch === '$') pickups.push({ type: 'heart', cell: { x, y } });
      return ch === '#' ? 'obstacle' : ch === 'o' ? 'hole' : ch === 'x' ? 'thorn' : 'floor';
    }),
  );
  const doorList: Door[] = doors.map((side) => ({ side, cell: DOOR_CELLS[side] }));
  return { tiles, doors: doorList, enemies, pickups };
}

const BOTH: Symmetry = { axes: ['vertical', 'horizontal'] };
const rules = (r: ReturnType<typeof room>, s: Symmetry = BOTH) => validateRoom(r, s).map((v) => v.rule);

describe('validateRoom', () => {
  it('accepts an open symmetric room', () => {
    const r = room(`
      .............
      .#.........#.
      .............
      ......Z......
      .............
      .#.........#.
      .............
    `);
    expect(rules(r)).toEqual([]);
  });

  it('rejects a door the others cannot reach', () => {
    const r = room(`
      ....#...#....
      ....#...#....
      ....#...#....
      ....#...#....
      ....#...#....
      ....#...#....
      ....#...#....
    `, ['up', 'left', 'right']);
    expect(rules(r)).toContain('door-unreachable');
  });

  it('rejects a zombie sealed away from the doors', () => {
    const r = room(`
      .............
      .............
      .....###.....
      .....#Z#.....
      .....###.....
      .............
      .............
    `);
    expect(rules(r)).toEqual(['walker-unreachable']);
  });

  it('accepts a turret on an island it can shoot from over the holes', () => {
    const r = room(`
      .............
      .............
      .....ooo.....
      .....oTo.....
      .....ooo.....
      .............
      .............
    `);
    expect(rules(r)).toEqual([]);
  });

  it('rejects a turret walled in so it can never be shot', () => {
    const r = room(`
      .............
      .............
      .....###.....
      .....#T#.....
      .....###.....
      .............
      .............
    `);
    expect(rules(r)).toEqual(['turret-unshootable']);
  });

  it('rejects terrain that breaks a declared mirror axis', () => {
    const r = room(`
      .............
      .##..........
      .............
      .............
      .............
      .##.......o..
      .............
    `);
    expect(rules(r, { axes: ['vertical'] })).toEqual(['asymmetric']);
  });

  it('only checks the axes a room declares', () => {
    const r = room(`
      .............
      .##.......##.
      .............
      .............
      .............
      .............
      .............
    `);
    expect(rules(r, { axes: ['vertical'] })).toEqual([]);
    expect(rules(r, { axes: ['horizontal'] })).toEqual(['asymmetric']);
  });

  it('lets the idea’s own feature break the symmetry', () => {
    // A jar opening on its right side.
    const r = room(`
      .............
      ....#####....
      ....#...#....
      ....#.Z......
      ....#...#....
      ....#####....
      .............
    `, ['left', 'right']);
    expect(rules(r, { axes: ['horizontal', 'vertical'] })).toEqual(['asymmetric']);
    expect(rules(r, { axes: ['horizontal', 'vertical'], feature: [{ x: 8, y: 3 }] })).toEqual([]);
  });

  it('rejects terrain on the tile just inside a door', () => {
    const r = room(`
      .............
      ......#......
      .............
      .............
      .............
      ......#......
      .............
    `);
    expect(rules(r)).toEqual(['door-blocked', 'door-blocked']);
  });

  it('rejects an enemy crowding a door', () => {
    const r = room(`
      .............
      .............
      .............
      .Z.........Z.
      .............
      .............
      .............
    `);
    expect(rules(r)).toEqual(['enemy-near-door', 'enemy-near-door']);
  });

  it('rejects spawns that share a cell or stand off the floor', () => {
    const r = room(`
      .............
      .............
      .............
      ......Z......
      .............
      .............
      .............
    `);
    r.enemies.push({ type: 'zombie', cell: { x: 6, y: 3 } });
    r.pickups.push({ type: 'key', cell: { x: 3, y: 3 } });
    r.tiles[3][3] = 'hole';
    r.tiles[3][9] = 'hole';
    expect(rules(r)).toEqual(['overlap', 'spawn-off-floor']);
  });

  it('accepts loot sealed away from the doors', () => {
    const r = room(`
      .............
      .............
      .....###.....
      .....#$#.....
      .....###.....
      .............
      .............
    `);
    expect(rules(r)).toEqual([]);
  });

  it('rejects a zombie hemmed in by thorns, since walkers cannot walk through them', () => {
    const r = room(`
      .............
      .............
      .....xxx.....
      .....xZx.....
      .....xxx.....
      .............
      .............
    `);
    expect(rules(r)).toEqual(['walker-unreachable']);
  });

  it('accepts a turret ringed by thorns, since shots fly over them', () => {
    const r = room(`
      .............
      .............
      .....xxx.....
      .....xTx.....
      .....xxx.....
      .............
      .............
    `);
    expect(rules(r)).toEqual([]);
  });

  it('rejects thorns on the tile just inside a door', () => {
    const r = room(`
      .............
      .............
      .............
      .x.........x.
      .............
      .............
      .............
    `);
    expect(rules(r)).toEqual(['door-blocked', 'door-blocked']);
  });

  it('rejects a spawn standing on a thorn', () => {
    const r = room(`
      .............
      .............
      ...x.....x...
      .............
      .............
      .............
      .............
    `);
    r.pickups.push({ type: 'heart', cell: { x: 3, y: 2 } });
    expect(rules(r, { axes: ['vertical'] })).toEqual(['spawn-off-floor']);
  });

  it('accepts a ghost sealed behind a wall, since it drifts through stone', () => {
    const r = room(`
      .............
      .............
      .....###.....
      .....#.#.....
      .....###.....
      .............
      .............
    `);
    r.enemies.push({ type: 'ghost', cell: { x: 6, y: 3 } });
    expect(rules(r)).toEqual([]);
  });

  it('still keeps a ghost off terrain and away from the doors', () => {
    const r = room(`
      .............
      .............
      .............
      .............
      .............
      .............
      .............
    `);
    r.enemies.push({ type: 'ghost', cell: { x: 1, y: 3 } });
    r.enemies.push({ type: 'ghost', cell: { x: 4, y: 2 } });
    r.tiles[2][4] = 'obstacle';
    r.tiles[2][8] = 'obstacle';
    r.tiles[4][4] = 'obstacle';
    r.tiles[4][8] = 'obstacle';
    expect(rules(r)).toEqual(['enemy-near-door', 'spawn-off-floor']);
  });

  it('requires at least one mirror axis', () => {
    expect(rules(room(`
      .............
      .............
      .............
      .............
      .............
      .............
      .............
    `), { axes: [] })).toEqual(['asymmetric']);
  });
});

/** Like `room`, plus `H` and `V`: a crusher sliding horizontally or vertically. */
function roomWithCrushers(picture: string, doors?: Direction[]) {
  const r = room(picture, doors);
  const crushers: Crusher[] = [];
  picture.trim().split('\n').map((row) => row.trim()).forEach((row, y) =>
    [...row].forEach((ch, x) => {
      if (ch !== 'H' && ch !== 'V') return;
      r.tiles[y][x] = 'crusher';
      crushers.push({ cell: { x, y }, axis: ch === 'H' ? 'horizontal' : 'vertical' });
    }),
  );
  return { ...r, crushers };
}

describe('validateRoom crusher lanes', () => {
  const MIDDLE_CRUSHER = (axis: 'H' | 'V') => `
    .............
    .............
    .............
    ......${axis}......
    .............
    .............
    .............
  `;

  it('accepts a lane that never stops on a door approach', () => {
    expect(rules(roomWithCrushers(MIDDLE_CRUSHER('V'), ['left', 'right']))).toEqual([]);
    expect(rules(roomWithCrushers(MIDDLE_CRUSHER('H'), ['up', 'down']))).toEqual([]);
  });

  it('rejects a lane that blocks a door approach once the crusher stops', () => {
    expect(rules(roomWithCrushers(MIDDLE_CRUSHER('V'), ['up', 'left', 'right']))).toEqual(['crusher-lane']);
    expect(rules(roomWithCrushers(MIDDLE_CRUSHER('H'), ['up', 'down', 'right']))).toEqual(['crusher-lane']);
  });

  it('rejects a lane whose stopped crusher seals a zombie away', () => {
    const r = roomWithCrushers(`
      H......#.....
      .....#.#.....
      .....#Z#.....
      .....###.....
      .............
      .............
      .............
    `, ['left', 'right']);
    expect(rules(r)).toContain('crusher-lane');
  });

  it('accepts a lane whose stopped crusher leaves every zombie a way out', () => {
    const r = roomWithCrushers(`
      H.......#....
      .....#.#.....
      .....#Z#.....
      .....###.....
      .............
      .............
      .............
    `, ['left', 'right']);
    expect(rules(r)).not.toContain('crusher-lane');
  });
});
